#!/usr/bin/bash
#TODO: POSIX
[[ $# -lt 2 ]] && exit 1 

STACK_TYPE=vstack
OUTPUT_NAME=out.jpg
POS_ARGS=() 

while [[ $# -gt  0 ]]; do
    case $1 in
	-h | --horizontal )
	    STACK_TYPE=hstack
	    shift
	    ;;
	-v | --vertical )
	    STACK_TYPE=vstack
	    shift
	    ;;
	-o | -out | --output)
	    OUTPUT_NAME=$2
	    shift 2
	    ;;
	-* | --* )
	    printf "$1 ?\n"
	    exit 1
	    ;;
	* ) 
	    POS_ARGS+=("$1")
	    shift
	    ;;
    esac
done 
set -- "${POS_ARGS[@]}" 
printf "joinimg-v1.0\ninput 1:\t\t$1\ninput 2:\t\t$2\norientation:\t\t$([[ $STACK_TYPE == vstack ]] && echo vertical || echo horizontal)\noutput filename:\t$OUTPUT_NAME\n" 
ffmpeg -hide_banner -loglevel error -i "$1" -i "$2" -filter_complex "$STACK_TYPE, format=yuv420p" "$OUTPUT_NAME"
exit 0
